/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedToolsIdLookupRouteImport } from './routes/_authenticated/tools/id-lookup'
import { Route as AuthenticatedSettingsWebhookGuideRouteImport } from './routes/_authenticated/settings/webhook-guide'
import { Route as AuthenticatedSettingsSyncRouteImport } from './routes/_authenticated/settings/sync'
import { Route as AuthenticatedSettingsCrmRouteImport } from './routes/_authenticated/settings/crm'
import { Route as AuthenticatedImportHistoryRouteImport } from './routes/_authenticated/import/history'
import { Route as AuthenticatedImportJobIdRouteImport } from './routes/_authenticated/import/$jobId'
import { Route as ApiPublicWebhooksGhlUnitAssociatedRouteImport } from './routes/api/public/webhooks/ghl/unit-associated'
import { Route as ApiPublicWebhooksGhlOpportunityStageRouteImport } from './routes/api/public/webhooks/ghl/opportunity-stage'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsIdLookupRoute =
  AuthenticatedToolsIdLookupRouteImport.update({
    id: '/tools/id-lookup',
    path: '/tools/id-lookup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWebhookGuideRoute =
  AuthenticatedSettingsWebhookGuideRouteImport.update({
    id: '/settings/webhook-guide',
    path: '/settings/webhook-guide',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSyncRoute =
  AuthenticatedSettingsSyncRouteImport.update({
    id: '/settings/sync',
    path: '/settings/sync',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCrmRoute =
  AuthenticatedSettingsCrmRouteImport.update({
    id: '/settings/crm',
    path: '/settings/crm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportHistoryRoute =
  AuthenticatedImportHistoryRouteImport.update({
    id: '/import/history',
    path: '/import/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportJobIdRoute =
  AuthenticatedImportJobIdRouteImport.update({
    id: '/import/$jobId',
    path: '/import/$jobId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhooksGhlUnitAssociatedRoute =
  ApiPublicWebhooksGhlUnitAssociatedRouteImport.update({
    id: '/api/public/webhooks/ghl/unit-associated',
    path: '/api/public/webhooks/ghl/unit-associated',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksGhlOpportunityStageRoute =
  ApiPublicWebhooksGhlOpportunityStageRouteImport.update({
    id: '/api/public/webhooks/ghl/opportunity-stage',
    path: '/api/public/webhooks/ghl/opportunity-stage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import/$jobId': typeof AuthenticatedImportJobIdRoute
  '/import/history': typeof AuthenticatedImportHistoryRoute
  '/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/settings/sync': typeof AuthenticatedSettingsSyncRoute
  '/settings/webhook-guide': typeof AuthenticatedSettingsWebhookGuideRoute
  '/tools/id-lookup': typeof AuthenticatedToolsIdLookupRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/api/public/webhooks/ghl/opportunity-stage': typeof ApiPublicWebhooksGhlOpportunityStageRoute
  '/api/public/webhooks/ghl/unit-associated': typeof ApiPublicWebhooksGhlUnitAssociatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import/$jobId': typeof AuthenticatedImportJobIdRoute
  '/import/history': typeof AuthenticatedImportHistoryRoute
  '/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/settings/sync': typeof AuthenticatedSettingsSyncRoute
  '/settings/webhook-guide': typeof AuthenticatedSettingsWebhookGuideRoute
  '/tools/id-lookup': typeof AuthenticatedToolsIdLookupRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/api/public/webhooks/ghl/opportunity-stage': typeof ApiPublicWebhooksGhlOpportunityStageRoute
  '/api/public/webhooks/ghl/unit-associated': typeof ApiPublicWebhooksGhlUnitAssociatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import/$jobId': typeof AuthenticatedImportJobIdRoute
  '/_authenticated/import/history': typeof AuthenticatedImportHistoryRoute
  '/_authenticated/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/_authenticated/settings/sync': typeof AuthenticatedSettingsSyncRoute
  '/_authenticated/settings/webhook-guide': typeof AuthenticatedSettingsWebhookGuideRoute
  '/_authenticated/tools/id-lookup': typeof AuthenticatedToolsIdLookupRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/api/public/webhooks/ghl/opportunity-stage': typeof ApiPublicWebhooksGhlOpportunityStageRoute
  '/api/public/webhooks/ghl/unit-associated': typeof ApiPublicWebhooksGhlUnitAssociatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import/$jobId'
    | '/import/history'
    | '/settings/crm'
    | '/settings/sync'
    | '/settings/webhook-guide'
    | '/tools/id-lookup'
    | '/import/'
    | '/inventory/'
    | '/api/public/webhooks/ghl/opportunity-stage'
    | '/api/public/webhooks/ghl/unit-associated'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/import/$jobId'
    | '/import/history'
    | '/settings/crm'
    | '/settings/sync'
    | '/settings/webhook-guide'
    | '/tools/id-lookup'
    | '/import'
    | '/inventory'
    | '/api/public/webhooks/ghl/opportunity-stage'
    | '/api/public/webhooks/ghl/unit-associated'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/import/$jobId'
    | '/_authenticated/import/history'
    | '/_authenticated/settings/crm'
    | '/_authenticated/settings/sync'
    | '/_authenticated/settings/webhook-guide'
    | '/_authenticated/tools/id-lookup'
    | '/_authenticated/import/'
    | '/_authenticated/inventory/'
    | '/api/public/webhooks/ghl/opportunity-stage'
    | '/api/public/webhooks/ghl/unit-associated'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksGhlOpportunityStageRoute: typeof ApiPublicWebhooksGhlOpportunityStageRoute
  ApiPublicWebhooksGhlUnitAssociatedRoute: typeof ApiPublicWebhooksGhlUnitAssociatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/id-lookup': {
      id: '/_authenticated/tools/id-lookup'
      path: '/tools/id-lookup'
      fullPath: '/tools/id-lookup'
      preLoaderRoute: typeof AuthenticatedToolsIdLookupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/webhook-guide': {
      id: '/_authenticated/settings/webhook-guide'
      path: '/settings/webhook-guide'
      fullPath: '/settings/webhook-guide'
      preLoaderRoute: typeof AuthenticatedSettingsWebhookGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/sync': {
      id: '/_authenticated/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AuthenticatedSettingsSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/crm': {
      id: '/_authenticated/settings/crm'
      path: '/settings/crm'
      fullPath: '/settings/crm'
      preLoaderRoute: typeof AuthenticatedSettingsCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/history': {
      id: '/_authenticated/import/history'
      path: '/import/history'
      fullPath: '/import/history'
      preLoaderRoute: typeof AuthenticatedImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/$jobId': {
      id: '/_authenticated/import/$jobId'
      path: '/import/$jobId'
      fullPath: '/import/$jobId'
      preLoaderRoute: typeof AuthenticatedImportJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/ghl/unit-associated': {
      id: '/api/public/webhooks/ghl/unit-associated'
      path: '/api/public/webhooks/ghl/unit-associated'
      fullPath: '/api/public/webhooks/ghl/unit-associated'
      preLoaderRoute: typeof ApiPublicWebhooksGhlUnitAssociatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ghl/opportunity-stage': {
      id: '/api/public/webhooks/ghl/opportunity-stage'
      path: '/api/public/webhooks/ghl/opportunity-stage'
      fullPath: '/api/public/webhooks/ghl/opportunity-stage'
      preLoaderRoute: typeof ApiPublicWebhooksGhlOpportunityStageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportJobIdRoute: typeof AuthenticatedImportJobIdRoute
  AuthenticatedImportHistoryRoute: typeof AuthenticatedImportHistoryRoute
  AuthenticatedSettingsCrmRoute: typeof AuthenticatedSettingsCrmRoute
  AuthenticatedSettingsSyncRoute: typeof AuthenticatedSettingsSyncRoute
  AuthenticatedSettingsWebhookGuideRoute: typeof AuthenticatedSettingsWebhookGuideRoute
  AuthenticatedToolsIdLookupRoute: typeof AuthenticatedToolsIdLookupRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportJobIdRoute: AuthenticatedImportJobIdRoute,
  AuthenticatedImportHistoryRoute: AuthenticatedImportHistoryRoute,
  AuthenticatedSettingsCrmRoute: AuthenticatedSettingsCrmRoute,
  AuthenticatedSettingsSyncRoute: AuthenticatedSettingsSyncRoute,
  AuthenticatedSettingsWebhookGuideRoute:
    AuthenticatedSettingsWebhookGuideRoute,
  AuthenticatedToolsIdLookupRoute: AuthenticatedToolsIdLookupRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksGhlOpportunityStageRoute:
    ApiPublicWebhooksGhlOpportunityStageRoute,
  ApiPublicWebhooksGhlUnitAssociatedRoute:
    ApiPublicWebhooksGhlUnitAssociatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
